Configuração inicial

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None) # Limite de colunas que serão mostradas
pd.set_option("display.max_rows", 100) # Limite de linhas que serão mostradas

plt.rcParams["figure.figsize"] = (10,6) # Tamanho das figuras, largura e altura

Importação da base

In [2]:
df_acre = pd.read_csv("base_dados/MICRODADOS_ENEM_2023_AC.csv")
print("Base carregada com sucesso.")

Base carregada com sucesso.

Checagem dos valores nulos

In [3]:
df_nulos = df_acre.isnull().sum().sort_values(ascending=False) # Contagem de nulos e ordenação decrescente
df_nulos = df_nulos.to_frame("Quantidade de nulos")
df_nulos["Porcentagem"] = (df_acre.isnull().sum() / len(df_acre) * 100).sort_values(ascending=False) # Coluna de porcentagem

print(df_nulos)

                        Quantidade de nulos  Porcentagem
SG_UF_ESC                             20077    82.709895
CO_UF_ESC                             20077    82.709895
NO_MUNICIPIO_ESC                      20077    82.709895
CO_MUNICIPIO_ESC                      20077    82.709895
TP_LOCALIZACAO_ESC                    20077    82.709895
TP_SIT_FUNC_ESC                       20077    82.709895
TP_DEPENDENCIA_ADM_ESC                20077    82.709895
TP_ENSINO                             17746    73.107028
CO_PROVA_CN                            9120    37.571064
TX_GABARITO_MT                         9120    37.571064
TX_RESPOSTAS_MT                        9120    37.571064
TX_RESPOSTAS_CN                        9120    37.571064
CO_PROVA_MT                            9120    37.571064
NU_NOTA_MT                             9120    37.571064
NU_NOTA_CN                             9120    37.571064
TX_GABARITO_CN                         9120    37.571064
NU_NOTA_CH                             8112    33.418472
NU_NOTA_LC                             8112    33.418472
CO_PROVA_LC                            8112    33.418472
TP_STATUS_REDACAO                      8112    33.418472
NU_NOTA_COMP3                          8112    33.418472
NU_NOTA_REDACAO                        8112    33.418472
NU_NOTA_COMP5                          8112    33.418472
TX_RESPOSTAS_CH                        8112    33.418472
TX_GABARITO_CH                         8112    33.418472
TX_RESPOSTAS_LC                        8112    33.418472
TX_GABARITO_LC                         8112    33.418472
CO_PROVA_CH                            8112    33.418472
NU_NOTA_COMP1                          8112    33.418472
NU_NOTA_COMP2                          8112    33.418472
NU_NOTA_COMP4                          8112    33.418472
TP_ANO_CONCLUIU                           0     0.000000
IN_TREINEIRO                              0     0.000000
TP_ESCOLA                                 0     0.000000
TP_ESTADO_CIVIL                           0     0.000000
TP_SEXO                                   0     0.000000
NU_ANO                                    0     0.000000
TP_FAIXA_ETARIA                           0     0.000000
NU_INSCRICAO                              0     0.000000
TP_ST_CONCLUSAO                           0     0.000000
TP_COR_RACA                               0     0.000000
TP_NACIONALIDADE                          0     0.000000
TP_PRESENCA_MT                            0     0.000000
CO_MUNICIPIO_PROVA                        0     0.000000
TP_LINGUA                                 0     0.000000
NO_MUNICIPIO_PROVA                        0     0.000000
SG_UF_PROVA                               0     0.000000
CO_UF_PROVA                               0     0.000000
TP_PRESENCA_CN                            0     0.000000
TP_PRESENCA_CH                            0     0.000000
TP_PRESENCA_LC                            0     0.000000
Q001                                      0     0.000000
Q002                                      0     0.000000
Q003                                      0     0.000000
Q004                                      0     0.000000
Q005                                      0     0.000000
Q006                                      0     0.000000
Q007                                      0     0.000000
Q008                                      0     0.000000
Q009                                      0     0.000000
Q010                                      0     0.000000
Q011                                      0     0.000000
Q012                                      0     0.000000
Q013                                      0     0.000000
Q014                                      0     0.000000
Q015                                      0     0.000000
Q016                                      0     0.000000
Q017                                      0     0.000000
Q018                                      0     0.000000
Q019                                      0     0.000000
Q020                                      0     0.000000
Q021                                      0     0.000000
Q022                                      0     0.000000
Q023                                      0     0.000000
Q024                                      0     0.000000
Q025                                      0     0.000000

Análise dos dados envolvendo escola

In [5]:
df_escolas = df_acre.dropna(subset=['TP_DEPENDENCIA_ADM_ESC', 'TP_LOCALIZACAO_ESC']).copy()

mapeamento_escola = {1: 'Pública', 2: 'Pública', 3: 'Pública', 4: 'Privada'}
mapeamento_localizacao = {1: 'Urbana', 2: 'Rural'}
df_escolas['LOCALIZACAO_ESC'] = df_escolas['TP_LOCALIZACAO_ESC'].map(mapeamento_localizacao)
df_escolas['TIPO_ESCOLA_ADM'] = df_escolas['TP_DEPENDENCIA_ADM_ESC'].map(mapeamento_escola)

colunas_notas = ['NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'NU_NOTA_REDACAO']
df_escolas['MEDIA_GERAL'] = df_escolas[colunas_notas].mean(axis=1)

print(f"Dataframe apenas com alunos com dados escolares preenchidos:", df_escolas.shape)

Dataframe apenas com alunos com dados escolares preenchidos: (4197, 79)

Comparação entre alunos de escola pública e alunos de escola privada (Média):

In [6]:
comparativo_adm = df_escolas.groupby('TIPO_ESCOLA_ADM')['MEDIA_GERAL'].mean().reset_index()
display(comparativo_adm)

  TIPO_ESCOLA_ADM  MEDIA_GERAL
0         Privada   614.151957
1         Pública   496.064239

Comparação entre alunos de escola em zona rural e zona urbana

In [7]:
comparativo_localizacao = df_escolas.groupby('LOCALIZACAO_ESC')['MEDIA_GERAL'].mean().reset_index()
display(comparativo_localizacao)

  LOCALIZACAO_ESC  MEDIA_GERAL
0           Rural   481.547852
1          Urbana   515.201094

In [9]:
df_nulos_escola = df_escolas.isnull().sum().sort_values(ascending=False) # Contagem de nulos e ordenação decrescente
print(df_nulos_escola)

NU_NOTA_MT                1229
TX_RESPOSTAS_MT           1229
TX_RESPOSTAS_CN           1229
TX_GABARITO_MT            1229
TX_GABARITO_CN            1229
CO_PROVA_MT               1229
CO_PROVA_CN               1229
NU_NOTA_CN                1229
TX_RESPOSTAS_CH           1045
TX_GABARITO_LC            1045
TX_GABARITO_CH            1045
CO_PROVA_LC               1045
CO_PROVA_CH               1045
NU_NOTA_LC                1045
NU_NOTA_CH                1045
NU_NOTA_COMP1             1045
TP_STATUS_REDACAO         1045
NU_NOTA_COMP2             1045
NU_NOTA_COMP3             1045
NU_NOTA_REDACAO           1045
NU_NOTA_COMP5             1045
NU_NOTA_COMP4             1045
TX_RESPOSTAS_LC           1045
MEDIA_GERAL               1038
TP_ENSINO                  254
TP_FAIXA_ETARIA              0
TP_COR_RACA                  0
NU_INSCRICAO                 0
NU_ANO                       0
TP_ESTADO_CIVIL              0
TP_SEXO                      0
CO_UF_ESC                    0
NO_MUNICIPIO_ESC             0
CO_MUNICIPIO_ESC             0
IN_TREINEIRO                 0
TP_ESCOLA                    0
TP_ANO_CONCLUIU              0
TP_ST_CONCLUSAO              0
TP_NACIONALIDADE             0
TP_SIT_FUNC_ESC              0
TP_LOCALIZACAO_ESC           0
TP_DEPENDENCIA_ADM_ESC       0
TP_PRESENCA_MT               0
TP_PRESENCA_CN               0
TP_PRESENCA_CH               0
TP_PRESENCA_LC               0
SG_UF_PROVA                  0
TP_LINGUA                    0
CO_UF_PROVA                  0
NO_MUNICIPIO_PROVA           0
CO_MUNICIPIO_PROVA           0
SG_UF_ESC                    0
Q001                         0
Q003                         0
Q002                         0
Q005                         0
Q006                         0
Q007                         0
Q008                         0
Q009                         0
Q010                         0
Q011                         0
Q004                         0
Q012                         0
Q013                         0
Q015                         0
Q014                         0
Q017                         0
Q018                         0
Q019                         0
Q016                         0
Q020                         0
Q021                         0
Q023                         0
Q022                         0
Q024                         0
Q025                         0
LOCALIZACAO_ESC              0
TIPO_ESCOLA_ADM              0
dtype: int64